TARGET=trapazoids

all:
	@echo ""
	@echo "Making all tests. -------------------------------------------"
	cd p2/; make
	@echo ""
	@echo "Done. -------------------------------------------------------"
	@echo "Go into test/p2 to test the integral approximation programs.."
	@echo ""

run:
	@echo ""
	@echo " Recompiling and running.."
	cd p2/; run clean
	cd p2/; run 8 
	@echo ""
	@echo "----------  Done   ----------"
	@echo ""
