#! /usr/bin/env bash

# eval "mpirun -n $2x $1"

function about()
{
    echo "-----------------------" 
    echo "  Usage Examples: "
    echo ""
    echo "      run generate_matrix 1"
    echo "      run generate_matrix 16"
    echo "      run matrixmult 1"
    echo "      run matrixmult 8"
    echo "      " 
    echo "  Run Make Example: " 
    echo "      " 
    echo "      run make" 
    echo "      run make matrixmult" 
    echo "-----------------------" 
    echo ""
}


echo "Run Manager"
echo ""
if [[ "$1" == "make" ]]; then
    if [[ ! -z "$2" ]]; then
        echo "  Executing: 'make CC=mpicc $2'"
        eval "make CC=mpicc $2"
    else
        echo "  Executing: 'make CC=mpicc'"
        eval "make CC=mpicc"
    fi
elif [[ ! -z "$1" ]]; then
    num_procs=" "
    if [[ ! -z "$2" ]]; then
        num_procs=" -n $2 " 
    fi
    echo "  Starting Run:"
    echo "      mpirun $num_procs $1"
    echo ""
    eval "mpirun $num_procs $1"
else
    about
    echo "  Did Nothing.. (no params)"
    echo ""
fi

echo "Done."
