#! /usr/bin/env bash

# eval "mpirun -n $2x $1"

function about()
{
    echo "-----------------------" 
    echo "  Usage Examples: "
    echo ""
    echo "      run generate_matrix 1"
    echo "      run generate_matrix 16"
    echo "      run gaussian 1"
    echo "      run gaussian 8"
    echo "      " 
    echo "  Run Make Example: " 
    echo "      " 
    echo "      run make" 
    echo "      run make gaussian" 
    echo "-----------------------" 
    echo ""
}


echo "Run Manager"
echo ""
if [[ "$1" == "make" ]]; then
    if [[ ! -z "$2" ]]; then
        echo "gcc -g -Wall -std=c99 -fopenmp  \
                    -O3 -funroll-loops -march=native -I./ \
                    -o gaussian $2 matrix.c \
                    -Wno-unused-result  \
                    -Wno-unused-variable  -lm"

        eval "gcc -g -Wall -std=c99 -fopenmp  \
                    -O3 -funroll-loops -march=native -I./ \
                    -o gaussian $2 matrix.c \
                    -Wno-unused-result  \
                    -Wno-unused-variable  -lm"
    else
        echo "gcc -g -Wall -std=c99 -fopenmp -D_GNU_SOURCE  \
                    -O3 -funroll-loops -march=native -I./  \
                    -o gaussian ./gaussian.c matrix.c  \
                    -Wno-unused-result  \
                    -Wno-unused-variable  -lm"
        eval "gcc -g -Wall -std=c99 -fopenmp  \
                    -O3 -funroll-loops -march=native -I./ \
                    -o gaussian ./gaussian.c matrix.c  \
                    -Wno-unused-result  \
                    -Wno-unused-variable  -lm"
    fi
elif [[ ! -z "$1" ]]; then
    num_procs=" "
    if [[ ! -z "$2" ]]; then
        num_procs="$2 " 
    fi
    echo "  Starting Run:"
    echo "       $1 $2 $3"
    echo ""
    eval " $1 $2 $3"
else
    about
    echo "  Did Nothing.. (no params)"
    echo ""
fi

echo "Done."
